FROM node:lts-alpine

WORKDIR /app

COPY package*.json ./

COPY prisma ./prisma

RUN npm install --include=optional

COPY . .

RUN npx prisma generate

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]