import {
	Cat,
	HouseHeart,
	PawPrint,
	Search,
	Plus,
	ClipboardList,
	Mail,
	UserGroup,
	Newspaper,
	HeartPlus,
	PenTool,
	Dog,
	Baby,
	Trees,
	CircleCheckBig,
	CircleX,
	CircleQuestionMark,
	Eye,
	TriangleAlert,
	Mars,
	Venus,
	CirclePause,
	CirclePlay,
	Handshake,
	CircleEllipsis,
	Phone,
	Ban,
	MapPinHouse,
	User,
	Syringe,
	ChevronDown,
	Clock,
	Star,
	BicepsFlexed
} from '@lucide/svelte';
import type { Component } from 'svelte';

export const iconMap: Record<string, Component> = {
	cat: Cat,
	house: HouseHeart,
	paw: PawPrint,
	search: Search,
	plus: Plus,
	clipboard: ClipboardList,
	mail: Mail,
	user: User,
	users: UserGroup,
	news: Newspaper,
	heart: HeartPlus,
	pen: PenTool,
	dog: Dog,
	baby: Baby,
	trees: Trees,
	CircleCheck: CircleCheckBig,
	CircleX: CircleX,
	CircleQuestionMark: CircleQuestionMark,
	Eye: Eye,
	alert: TriangleAlert,
	mars: Mars,
	venus: Venus,
	CirclePause: CirclePause,
	CirclePlay: CirclePlay,
	Handshake: Handshake,
	other: CircleEllipsis,
	phone: Phone,
	blacklist: Ban,
	map: MapPinHouse,
	syringe: Syringe,
	chevronDown: ChevronDown,
	clock: Clock,
	star: Star,
	biceps: BicepsFlexed
};
